'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como ResGen ou Visual Studio.
    'Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    'com a opção /str, ou recrie o projeto do VS.
    '''<summary>
    '''  Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ManagerCore.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread atual para todas as
        '''  pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;pt-br&quot;&gt;
        '''&lt;head&gt;
        '''	&lt;meta charset=&quot;UTF-8&quot;&gt;
        '''	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        '''	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        '''	&lt;title&gt;Email&lt;/title&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property DefaultEmail() As String
            Get
                Return ResourceManager.GetString("DefaultEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;License Version=&quot;1&quot;&gt;
        '''	&lt;LicenseKey&gt;&lt;/LicenseKey&gt;
        '''	&lt;LicenseToken&gt;&lt;/LicenseToken&gt;
        '''	&lt;CustomerDocument&gt;&lt;/CustomerDocument&gt;
        '''	&lt;CustomerName&gt;&lt;/CustomerName&gt;
        '''	&lt;ExpirationDate&gt;0001-01-01 00:00:00&lt;/ExpirationDate&gt;
        '''	&lt;ManagerAgentPassword&gt;&lt;/ManagerAgentPassword&gt;
        '''	&lt;ManagerAgentUsername&gt;&lt;/ManagerAgentUsername&gt;	
        '''	&lt;LastOnlineValidation&gt;0001-01-01 00:00:00&lt;/LastOnlineValidation&gt;
        '''&lt;/License&gt;.
        '''</summary>
        Friend ReadOnly Property License() As String
            Get
                Return ResourceManager.GetString("License", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;Setting Version=&quot;2&quot;&gt;
        '''	&lt;Company&gt;
        '''		&lt;Document&gt;&lt;/Document&gt;
        '''		&lt;LogoLocation&gt;&lt;/LogoLocation&gt;
        '''		&lt;Name&gt;&lt;/Name&gt;
        '''		&lt;Shortname&gt;&lt;/Shortname&gt;
        '''		&lt;CityDocument&gt;&lt;/CityDocument&gt;
        '''		&lt;StateDocument&gt;&lt;/StateDocument&gt;
        '''		&lt;Address&gt;
        '''			&lt;ZipCode&gt;&lt;/ZipCode&gt;
        '''			&lt;Street&gt;&lt;/Street&gt;
        '''			&lt;Number&gt;&lt;/Number&gt;
        '''			&lt;Complement&gt;&lt;/Complement&gt;
        '''			&lt;District&gt;&lt;/District&gt;
        '''			&lt;City&gt;&lt;/City&gt;
        '''			&lt;State&gt;&lt;/State&gt;
        '''		&lt;/Address&gt;
        '''		&lt;Contact&gt;
        '''			&lt;Phone1&gt;&lt;/Phone1&gt;
        '''			&lt;Phone2&gt;&lt;/Phone2&gt;
        '''			&lt;CellPhone&gt;&lt;/CellP [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Setting() As String
            Get
                Return ResourceManager.GetString("Setting", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
