INSERT INTO visitschedule
(
    creation,
    statusid,
    scheduleddate,
    performeddate,
    calltypeid,
    customerid,
    personcompressorid,
    technicianid,
    instructions,
    evaluationid,
    overridedvisitscheduleid,
    lastupdate,
    userid
)
VALUES
(
    @creation,
    @statusid,
    @scheduleddate,
    @performeddate,
    @calltypeid,
    @customerid,
    @personcompressorid,
    @technicianid,
    @instructions,
    @evaluationid,
    @overridedvisitscheduleid,
    @lastupdate,
    @userid
);