INSERT INTO evaluation
(
	creation,
    statusid,
	evaluationtypeid,
	needproposalid,
	evaluationdate,
	starttime,
	endtime,
	evaluationnumber,
	customerid,
	responsible,
	personcompressorid,
	horimeter,
	manualaverageworkload,
	averageworkload,
	technicaladvice,
	documentname,
	signaturename,
	rejectreason,
	userid
)
VALUES
(
	@creation,
	@statusid,
	@evaluationtypeid,
	@needproposalid,
	@evaluationdate,
	@starttime,
	@endtime,
	@evaluationnumber,
	@customerid,
	@responsible,
	@personcompressorid,
	@horimeter,
	@manualaverageworkload,
	@averageworkload,
	@technicaladvice,
	@documentpath,
	@signaturepath,
	@rejectreason,
	@userid
);
