INSERT INTO visitschedule
(
    creation,
    statusid,
    visitdate,
    visittypeid,
    customerid,
    personcompressorid,
    instructions,
    evaluationid,
    synchronized,
    lastupdate,
    userid
)
VALUES
(
    @creation,
    @statusid,
    @visitdate,
    @visittypeid,
    @customerid,
    @personcompressorid,
    @instructions,
    @evaluationid,
    @synchronized,
    @lastupdate,
    @userid
);